weights_path = '/home/hikkav/AhegaoProject/mobilenet_age_gender/models/DMNfullmodel.h5'
arch_path='/home/hikkav/AhegaoProject/mobilenet_age_gender/models/MobileNet.json'
img_folder='/home/hikkav/AhegaoProject/imdb_crop/'
path_to_hist='/home/hikkav/AhegaoProject/history_of_mobilenets/'
num_classes1 = 21
n_neurons = 8000
img_size = 128
n_channels = 3
n_kernels = 4
dim = (img_size, img_size, n_channels)
